#ifndef READFILE_H_
#define READFILE_H_

#define PLX_RGB_MASK 0x8000
#define PLX_SHADE_MODE_MASK	0x6000
#define PLX_2SIDED_MASK 0X1000
#define PLX_COLOIR_MASX 0x0fff
#define PLX_COLOR_MODE_RGB_FLAG 0x8000
#define PLX_COLOR_MODE_INDEXED_FLAG 0x000

#define PLX_2SIDED_FLAG 0x1000
#define PLX_1SIDED_FLAG 0x0000

#define PLX_SHADE_MODE_PURG_FLAG 0x0000
#define PLX_SHADE_MODE_CONSTANT_FLAG  0x0000
#define PLX_SHADE_MODE_FLAT_FLAG  0x2000
#define PLX_SHADE_MODE_GOURAUD_FLAG 0x4000
#define PLX_SHADE_MODE_PHONG_FLAG 0x6000
#define PLX_SHADE_MODE_FASTPHONG_FLAG 0x6000

#define POLY3DV1_ATTR_2SIDED
#define POLY4DV1_ATTR_TRANSPARENT
#define POLY4DV1_ATTR_8BITCOLOR
#define POLY4DV1_ATTR_RGB16
#define POLY4DEV_ATTR_RGB24


#define POLY3DV1_SHADE_MODE_PURG_FLAG 0x0000
#define POLY3DV1_SHADE_MODE_CONSTANT_FLAG  0x0000
#define POLY3DV1_SHADE_MODE_FLAT_FLAG  0x2000
#define POLY3DV1_SHADE_MODE_GOURAUD_FLAG 0x4000
#define POLY3DV1_SHADE_MODE_PHONG_FLAG 0x6000
#define POLY3DV1_SHADE_MODE_FASTPHONG_FLAG 0x6000

#define POLY4DV1_STATE_ACTIVE  0x0001
#define POLY4DV1_STATE_CLIPPED 0x0002
#define POLY4DV1_STATE_BACKFACE 0x0004

#define OBJECT4DV1_MAX_VERTICES 64 
#define OBJECT4DV1_MAX_POLYS   64

#define OBJECT4DV1_STATE_ACTIVE  0x0001
#define OBJECT4DV1_STATE_VISIBLE 0x0002
#define OBJECTDV1_STATE_CULLED   0x0004

#define RENDERLIST4DV1_MAX_POLYS 128
#define TRANSFORM_LOCAL_ONLY  0
#define TRANSFORM_TRANS_ONLY  1
#define TRANSFORM_LOCAL_TO_TRANS  3

#define CULL_OBJECT_X_PLANE
#define CULL_OBJECT_Y_PLANE
#define CULL_ONJECT_Z_PLANE
#define CULL_OBJECT_XYZ_PLANES
#define CAM_ROT_SEQ_XYZ
#define CAM_POT_SEQ_YXZ
#define CAM_POT_SEQ_XZY
#define CAM_POT_SEQ_YZX
#define CAM_POT_SEQ_ZYX
#define CAM_POT_SEQ_ZXY

#define CAM_PROJ_NORMALIZED
#define CAM_PROJ_SCREEN
#define CAM_PROJ_FOV90

#define CAM_MODEL_EULER
#define CAM_MODE_UVN

#define CAM_MODE_SIMPLE
#define CAM_SPHERICAL

extern void Open_Error_File(const char* filename);
#endif